import os
import sys
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

# Get your API key
api_key = os.getenv("MY_API_KEY")
if not api_key:
    raise ValueError("API key not found. Please set MY_API_KEY in your .env file.")

# Add parent directory to path so we can import llm_pipeline and data_classes
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from llm_pipeline.llm_recipe_generator import RecipeLLM
from data_classes.UserProfile import UserProfile
from llm_pipeline.ranker import Ranker
from data_classes.Recipes import Recipe


# Initialize LLM with API key
llm = RecipeLLM(api_key=api_key)

# Example user profile (autogenerated user_id)
user = UserProfile(
    dietary_restrictions={"Vegetarian"},
    cuisine_preferences=["Italian"],
    budget_usd=20,
    time_available=60,  # minutes
    appliances={"Oven", "Blender"}
)

# Generate recipes
all_recipes = []
n_recipes = 5

for _ in range(n_recipes):
    recipes = llm.generate_recipes(user, n_recipes=1)
    for r in recipes:
        try:
            if isinstance(r, dict):
                all_recipes.append(r)
            elif isinstance(r, str):
                # Try to parse JSON string into dict
                all_recipes.append(json.loads(r))
            else:
                # If it’s already some other type (e.g., Recipe object), convert to dict
                all_recipes.append(r.__dict__)
        except Exception as e:
            print("Failed to parse recipe as dict:", e)
            print("Raw output:", r)

# Print the result
ranker = Ranker(api_key=os.getenv("MY_API_KEY"))
sorted_recipes = ranker.rank(user_profile=user, recipes=all_recipes)

print("\nGenerated Recipes:\n")
for i, recipe in enumerate(sorted_recipes, start=1):
    print(f"Recipe {i}: {recipe.title}")
    print(f"  Cuisine: {recipe.cuisine}")
    print(f"  Estimated Time: {recipe.cook_minutes} minutes")
    print(f"  Estimated Cost: ${recipe.price_estimate_usd}")
    print(f"  Tags: {', '.join(recipe.tags or [])}")
    print(f"  Appliances Needed: {', '.join(recipe.appliances or [])}")
    print("  Ingredients:")
    for name, qty, unit in recipe.ingredients or []:
        print(f"    - {name}: {qty} {unit}")
    print("  Procedure:")
    print(f"    {recipe.procedure}\n")



